name: nxv
channels:
  - conda-forge
  - mantid/label/nightly
dependencies:
  - python
  - poetry
  - numpy
  - scipy
  - matplotlib
  - pycifrw
  - h5py
  - pyvista>=0.45.2
  - pytest
  - mantid
  - scikit-learn
  - scikit-image
  - astropy
  - dill
  - psutil
  - multiprocess
  - black
  - pip:
    - blinker
    - nova-mvvm
    - nova-trame>=0.20.2
    - trame-matplotlib
    - trame-vtk
